# Generated by Django 4.2.7 on 2023-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_chat',
            field=models.BooleanField(default=False),
        ),
    ]
