# Generated by Django 4.2.7 on 2023-12-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_in_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_page',
            field=models.IntegerField(null=True),
        ),
    ]
